from playwright.sync_api import sync_playwright
import time
with sync_playwright() as p:
    browser = p.chromium.launch(headless=False, slow_mo=50)
    page = browser.new_page()
    page.goto('https://secure.incometax.gov.bd/Registration/Login')
    # time.sleep(1)
    page.fill('input#LOGON_NAME', 'nbr_user_name')
    # time.sleep(1)
    page.fill('input#LOGON_PASS','nbr_password')
    # time.sleep(1)
    page.click('button[type=submit]') 
    # time.sleep(60)
    page.goto('https://secure.incometax.gov.bd/TinVerifyThirdParty')
    page.fill('input#NEW_TIN','560234776651')
    # page.fill('input#NEW_TIN_NAME','BBLRASHED')
    page.fill('input#ASSES_NAME', 'Md. Ridwan Mizan')
    page.select_option('select#DOB_DAY','22')
    page.select_option('select#DOB_MONTH', '07')
    page.select_option('select#DOB_YEAR', '1992')
    page.click('input#btnSearch')
    response = page.locator('//*/form/fieldset/div[2]/table/tbody/tr/td/span').text_content()
    print(response)
    time.sleep(60)